# Boolean Networks & Cellular Automaton

## Short introduction to python
The tutorial will be based on `python`. A basic understanding of programming and the python language will be sufficient to follow the examples. 

Many good basic python tutorials and introductions exist, for instance see

- https://www.learnpython.org/ -  interactive python tutorial
- https://docs.python.org/3/tutorial/index.html - official tutorial, more in depth

For installation instructions see for instance https://wiki.python.org/moin/BeginnersGuide/Download

This tutorial and all information related to it is available online at
https://github.com/matthiaskoenig/modelling_ws2018

To follow the tutorial a basic `python3` installation with the packages listed in `requirements.txt` is needed.
```
numpy
pandas
matplotlib
```

If you have any questions or need help please contact konigmatt@googlemail.com

## Boolean Networks

- A boolean network consists of nodes (which have a boolean state) and connections between the states (inputs for nodes).
- The boolean states can be either 0 or 1.
- Every node (state) in the boolean network has a rule which specifies the output of the node (state) for all possible combinations of inputs. 
- Based on the given rule for a node the node state is updated.
- Simulations start from an initial state of the network. This is the state of all nodes at the begin of the simulation.

General Properties of Boolean Networks:

- Fixed topology (doesn’t change with time)
- Dynamic (states evolve over time, updates happen at discrete time steps)
- Synchronous (update of all states occurs at the same time)
- Node States: Deterministic (based on rules), discrete (binary)
- Gate Function: Boolean (rules which calculate the update for the state, return discrete new state)
- Flow: Information

For one dimensional input of a given node in a boolean network the possible unary boolean operators are

- IDENTITY (`[0]->[0], [1]->[1]`) 
- INVERSE (`[0]->[1], [1]->[0]`)
- ZERO (`[0]->[0], [1]->[0]`)
- ONE (`[0]->[1], [1]->[1]`)

For two dimensional inputs possible logical operations (rules) are for instance

- AND (`[1,1]->[1], [1,0]->[0], [0,1]->[1], [0,0]->[0]`) 
- OR
- XOR
- NOR
- ...

An overview over the truth tables (boolean rules) for unary and binary operations can be found here https://en.wikipedia.org/wiki/Truth_table

### Task 1
Within this task we will simulate a boolean network by applying the rules repeatedly starting from an intial state, thereby updating the state vector `[X1, X2]`.


<img src="Example1.png" width="200"/>

* Write a computer program which simulates the simple boolean networks consisting of the two nodes `X1` and `X2` with the initial state `[X1, X2](0) = [0, 1]`. The boolean rules for updating `X1` based on the input from `X2`, and for updating X2 based on the input of `X1` are the unary `INVERSE` rule. Simulate the model for 20 steps. What is the final state of the boolean network?
* What are the possible trajectories of the boolean network, i.e. which sequence of states are possible? (hint: simulate the network for all possible initial states)

In [80]:
# simple solution
# - handle states as boolean, just store the states 
N = 20  # number of steps
states = [(False, True)]  # initial state
for k in range(N):
    # get state of last step
    x = states[k]
    print(k, ':', x)
    
    # update state by applying rules
    x_new = (not x[0], not x[1])
    
    # store new state
    states.append(x_new)

print(states)

0 : (False, True)
1 : (True, False)
2 : (False, True)
3 : (True, False)
4 : (False, True)
5 : (True, False)
6 : (False, True)
7 : (True, False)
8 : (False, True)
9 : (True, False)
10 : (False, True)
11 : (True, False)
12 : (False, True)
13 : (True, False)
14 : (False, True)
15 : (True, False)
16 : (False, True)
17 : (True, False)
18 : (False, True)
19 : (True, False)
[(False, True), (True, False), (False, True), (True, False), (False, True), (True, False), (False, True), (True, False), (False, True), (True, False), (False, True), (True, False), (False, True), (True, False), (False, True), (True, False), (False, True), (True, False), (False, True), (True, False), (False, True)]


Now analyse all possible states of the network. For this we have to start the network from all possible initial states.

In [81]:
# - define functions to do recurring work,
# - generalize the solution so it can be applied to a broader field
states_init = [
    [True, True], 
    [False, False],
    [True, False],
    [False, True]
]

def f_inverse(x):
    """Inverse the given state"""
    return [not xel for xel in x]
    
def simulate(x0, f_rules, steps=10):
    """ Simulates the boolean network from initial state by applying the given rules.
        x0: initial state (boolean vector)
        rules: 
    """
    states = [x0]
    for k in range(steps):
        x = states[k]
        states.append(f_rules(x))
    return states

from pprint import pprint
for x0 in states_init:
    pprint("x0 = {}".format(x0))
    states = simulate(x0, f_rules=f_inverse)
    pprint(states)
    print("-" * 80)

'x0 = [True, True]'
[[True, True],
 [False, False],
 [True, True],
 [False, False],
 [True, True],
 [False, False],
 [True, True],
 [False, False],
 [True, True],
 [False, False],
 [True, True]]
--------------------------------------------------------------------------------
'x0 = [False, False]'
[[False, False],
 [True, True],
 [False, False],
 [True, True],
 [False, False],
 [True, True],
 [False, False],
 [True, True],
 [False, False],
 [True, True],
 [False, False]]
--------------------------------------------------------------------------------
'x0 = [True, False]'
[[True, False],
 [False, True],
 [True, False],
 [False, True],
 [True, False],
 [False, True],
 [True, False],
 [False, True],
 [True, False],
 [False, True],
 [True, False]]
--------------------------------------------------------------------------------
'x0 = [False, True]'
[[False, True],
 [True, False],
 [False, True],
 [True, False],
 [False, True],
 [True, False],
 [False, True],
 [True, False],
 [False, True],
 

In [89]:
# use appropriate data structures
# appending to a vector is always a bad idea
import numpy as np
from pprint import pprint

ndstates_init = [
    np.array([True, True]), 
    np.array([False, False]),
    np.array([True, False]),
    np.array([False, True])
]
# print(type(ndstates_init[0]))
# x0 = ndstates_init[2]
# print(x0)
# print(x0.shape)
# print(x0.dtype)

def f_ndinverse(x):
    """Inverse the given state"""
    return np.invert(x)
    
def ndsimulate(x0, f_rules, steps=10):
    """ Simulates the boolean network from initial state by applying the given rules.
        x0: initial state (boolean vector)
        rules: 
    """
    pprint("x0 = {}".format(x0))
    states = np.zeros(shape=(steps+1, x0.size), dtype=bool)
    states[0, :] = x0
    
    for k in range(steps):
        states[k+1, :] = f_rules(states[k, :])
    
    # cast for printing
    pprint(states.astype(np.int))
    print("-" * 80)
        
    return states

for x0 in ndstates_init:
    ndsimulate(x0, f_rules=f_ndinverse)
    

'x0 = [ True  True]'
array([[1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1]])
--------------------------------------------------------------------------------
'x0 = [False False]'
array([[0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0]])
--------------------------------------------------------------------------------
'x0 = [ True False]'
array([[1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0]])
--------------------------------------------------------------------------------
'x0 = [False  True]'
array([[0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1]])
---------

### Task 2
<img src="Example2.png" width="200"/>

* Simulate the following more complex boolean network consisting of 5 nodes (reuse the code from task 1)
* The update rules are given by

```
X1 = INVERSE(X4)
X5 = IDENTIY(X4)
X2 = OR(X1, X5)
X3 = OR(X1, X5)
X4 = XOR(X3, X2)
```


* What are the possible trajectories of the boolean network, i.e. which final states (or cycles of states) are reached? (hint: simulate the network for all possible initial states)

In [84]:
states_init = [
    [0,0,0,0,0],
    
    [1,0,0,0,0],
    [0,1,0,0,0],
    [0,0,1,0,0],
    [0,0,0,1,0],
    [0,0,0,0,1],
    
    [1,1,0,0,0],
    [1,0,1,0,0],
    [1,0,0,1,0],
    [1,0,0,0,1],
    [0,1,1,0,0],
    [0,1,0,1,0],
    [0,1,0,0,1],
    [0,0,1,1,0],
    [0,0,1,0,1],
    [0,0,0,1,1],
    
    [1,1,1,0,0],
    [1,1,0,1,0],
    [1,1,0,0,1],
    [1,0,1,1,0],
    [1,0,1,0,1],
    [1,0,0,1,1],
    [0,1,1,1,0],
    [0,1,1,0,1],
    [0,0,1,1,1],
    
    [1,1,1,1,0],
    [1,1,1,0,1],
    [1,1,0,1,1],
    [1,0,1,1,1],
    [0,1,1,1,1],
    
    [1,1,1,1,1],
]
print(len(states_init))
print(2**5)

31
32


In [95]:
# Think about similarities, often there are tricks which simplify things, generalize things
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.packbits.html
# Unpacks elements of a uint8 array into a binary-valued output array.

# binary numbers
states_init = [bin(k) for k in range(32)]
# print(states_init)

# uint8 vector (8 bits)
states_int = np.linspace(0, 31, num=32, dtype=np.uint8) # (32,)
states_int = np.reshape(states_int, (32, 1)) # (32, 1)
# print(states_int)

ndstates_init = np.unpackbits(states_int, axis=1)
ndstates_init = ndstates_init[:, 3:]
print(ndstates_init)

[[0 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 0 1 1]
 [0 0 1 0 0]
 [0 0 1 0 1]
 [0 0 1 1 0]
 [0 0 1 1 1]
 [0 1 0 0 0]
 [0 1 0 0 1]
 [0 1 0 1 0]
 [0 1 0 1 1]
 [0 1 1 0 0]
 [0 1 1 0 1]
 [0 1 1 1 0]
 [0 1 1 1 1]
 [1 0 0 0 0]
 [1 0 0 0 1]
 [1 0 0 1 0]
 [1 0 0 1 1]
 [1 0 1 0 0]
 [1 0 1 0 1]
 [1 0 1 1 0]
 [1 0 1 1 1]
 [1 1 0 0 0]
 [1 1 0 0 1]
 [1 1 0 1 0]
 [1 1 0 1 1]
 [1 1 1 0 0]
 [1 1 1 0 1]
 [1 1 1 1 0]
 [1 1 1 1 1]]


In [97]:
def ndsimulate(x0, f_rules, steps=5):
    """ Simulates the boolean network from initial state by applying the given rules.
        x0: initial state (boolean vector)
        f_rules: rules for the network 
    """
    pprint("x0 = {}".format(x0))
    states = np.zeros(shape=(steps+1, x0.size), dtype=bool)
    
    states[0, :] = x0
    for k in range(steps):
        states[(k+1), :] = f_rules(states[k, :])
        
    pprint(states.astype(np.int8))
    print("-" * 80)
        
    return states

def f_task2(x):
    """
    X1 = INVERSE(X4)
    X5 = IDENTIY(X4)
    X2 = OR(X1, X5)
    X3 = OR(X1, X5)
    X4 = XOR(X3, X2)
    """
    y = np.zeros_like(x)
    y[0] = np.invert(x[3])
    y[4] = x[3]
    y[1] = x[0] or x[4]
    y[2] = x[0] or x[4]
    # xor hack
    y[3] = x[2] or x[1]
    if (x[2] and x[1]):
        y[3] = False
    return y
    
for x0 in ndstates_init:
    states = ndsimulate(x0, f_rules=f_task2)

'x0 = [0 0 0 0 0]'
array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0]], dtype=int8)
--------------------------------------------------------------------------------
'x0 = [0 0 0 0 1]'
array([[0, 0, 0, 0, 1],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0]], dtype=int8)
--------------------------------------------------------------------------------
'x0 = [0 0 0 1 0]'
array([[0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0]], dtype=int8)
--------------------------------------------------------------------------------
'x0 = [0 0 0 1 1]'
array([[0, 0, 0, 1, 1],
       [0, 1, 1, 0, 1],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0]], dtype=int8)
-----------------------------------------------------

## Cellular automaton

A cellular automaton is a discrete model studied in computer science, mathematics, physics, complexity science, theoretical biology and microstructure modeling. 

<img src="Gospers_glider_gun.gif" width="200"/>

- A cellular automaton consists of a regular grid of cells, each in one of a finite number of states, such as on and off. 
- For each cell, a set of cells called its neighborhood is defined relative to the specified cell. 
- An initial state (time t = 0) is selected by assigning a state for each cell. 
- A new generation is created (advancing t by 1), according to some fixed rule (generally, a mathematical function) that determines the new state of each cell in terms of the current state of the cell and the states of the cells in its neighborhood. 
- Typically, the rule for updating the state of cells is the same for each cell and does not change over time, and is applied to the whole grid simultaneously.

For more information see https://en.wikipedia.org/wiki/Cellular_automaton.

A more in depth introduction with hints how to solve the task is given in https://natureofcode.com/book/chapter-7-cellular-automata/

### Task 3
Build and simulate the simple cellular automaton with the following characteristics:

- **Grid**: We will use the simplest possible grid, which is one-dimensional: a line of cells.
- **States**: The simplest set of states (beyond having only one state) are the two possible states per cell: 0 or 1.
- **Neighborhood**: The simplest neighborhood in one dimension for any given cell would be the cell itself and its two adjacent neighbors: one to the left and one to the right.
- **Rules**: Define how a cell is updated based on its neighborhood. The simplest rules are identical rules for every cell.

For the update rules we need to define an outcome (new state value 0 or 1) for a cell based on its current neighborhood.
The following rules are applied:

```
neighborhood (with cell in the center) -> new state of cell
000 -> 0
001 -> 1
010 -> 0
011 -> 1
100 -> 1
101 -> 0
110 -> 1
111 -> 0
```
- the one dimensional grid contains `101` cells
- the initial state of all cells is 0, with exception of the cell in the middle of the grid which starts with state 1